version: '3'
services:
  callbook:
    build:
        context: ./callbook
        dockerfile: Dockerfile
    ports:
        - "8005:8005"
    volumes:
        - ./callbook:/srv/web:ro
    environment:
        - PYTHONUNBUFFERED=1
